name: Solicitud de vacaciones
description: Solicitar vacaciones

title: "[VACACIONES] "

body:
  - type: input
    id: empleado
    attributes:
      label: Empleado
      placeholder: Nombre y apellidos
    validations:
      required: true

  - type: input
    id: fecha_inicio
    attributes:
      label: Fecha inicio
      placeholder: YYYY-MM-DD
      description: Ejemplo 2026-09-01
    validations:
      required: true

  - type: input
    id: fecha_fin
    attributes:
      label: Fecha fin
      placeholder: YYYY-MM-DD
      description: Ejemplo 2026-09-30
    validations:
      required: true

  - type: textarea
    id: comentarios
    attributes:
      label: Comentarios

