name: Solicitud de vacaciones
description: Solicitar días de vacaciones
title: "[VACACIONES] "
body:
  - type: input
    id: empleado
    attributes:
      label: Empleado

  - type: input
    id: fecha_inicio
    attributes:
      label: Fecha inicio

  - type: input
    id: fecha_fin
    attributes:
      label: Fecha fin

  - type: textarea
    id: comentarios
    attributes:
      label: Comentarios
