name: Solicitud de vacaciones
description: Solicitar vacaciones
title: "[VACACIONES] "

body:
  
  - type: input
    id: employee
    attributes:
      label: Empleado
      placeholder: Nombre y apellidos
    validations:
      required: true
  
  - type: input
    id: start
    attributes:
      label: Fecha inicio
      placeholder: YYYY-MM-DD
    validations:
      required: true

  - type: input
    id: end
    attributes:
      label: Fecha fin
      placeholder: YYYY-MM-DD
    validations:
      required: true

  - type: dropdown
    id: type
    attributes:
      label: Tipo
      options:
        - vacation
        - asuntos propios
        - baja médica
        - Permiso Especial/Mudanza
    validations:
      required: true

  - type: dropdown
    id: status
    attributes:
      label: Estado
      options:
        - approved
        - pending
        - rejected
    validations:
      required: true

  - type: textarea
    id: notes
    attributes:
      label: Comentarios
      placeholder: Vacaciones de verano
